FROM bitnami/pytorch:latest
LABEL maintainer "jeongin <jeongin@naver.com>"

WORKDIR /app
COPY app/utils.py .
COPY app/main.py .
RUN pip3 install flask re
ENV LOGPATH='/data'
ENV DATAPAHT='/data'
ENTRYPOINT ["python3"]
CMD ["main.py"]