FROM python:3.9
LABEL maintainer "jeongin <jeongin@naver.com>"

WORKDIR /app
COPY app/utils.py .
COPY app/main.py .
RUN pip3 install flask
ENV LOGPATH='/data'
ENV DATAPATH='/data'
ENTRYPOINT ["python3"]
CMD ["main.py"]