name: Python Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install flask

    - name: Set PYTHONPATH
      run: echo "export PYTHONPATH=$PYTHONPATH:$(pwd)/app" >> $GITHUB_ENV
      
    - name: Add __init__.py file
      run: touch app/__init__.py
      
    - name: Run tests
      run: python -m unittest app/utils.py
      
    - name: Run tests
      run: python -m unittest app/test.py

